[package]
id = splunk-app-template
version = 1.0.0
check_for_updates = false

[ui]
is_visible = true
label = Splunk App Template

[launcher]
author = Benjamin
description = Base template for all Splunk GitOps apps
version = 1.0.0

[install]
state = enabled
